version: '3'

services:
    es:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.1
        environment:
            - cluster.name=es
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - es-network
    searchbackend:
        build:
            context: server
            dockerfile: Dockerfile
            args:
                     JAR_FILE: search-server-1.0.0.jar
        ports:
            - 7111:80
        restart: on-failure
        depends_on:
            - es
        links:
            - es:es
        networks:
            - es-network
    searchfrontend:
        build:
            context: client
            dockerfile: Dockerfile
        ports:
            - 4200:80
        depends_on:
            - searchbackend
        networks:
            - es-network

networks:
    es-network:
        driver: bridge
