server:
  port: 7111
  servlet:
    application-display-name: Search
    context-path: /ws-search

spring:
  data:
    elasticsearch:
      cluster-nodes: es:9300
      cluster-name: es
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      fail-on-empty-beans: false
